name: AHJ-Working-with-HTML-forms

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Deploy to GitHub Pages
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "Aleksandr Mamontov"
          git config --global user.email "mamont861@yandex.ru"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Aleksandr861/AHJ-Working-with-HTML-forms.git
          npx gh-pages -d dist --branch gh-pages "GitHub Actions <action@github.com>"